/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import authentiocation.AuthenticationController;
import authentiocation.FormLogin;
import authentiocation.FormUser;
import cuti.FormCuti;
import jabatan.FormJabatan;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import karyawan.FormKaryawan;
import keterlamabatan.FormKeterlambatan;
import lembur.FormLembur;
import penggajian.FormPenggajian;

/**
 *
 * @author Farhan Fadila
 */
public class HomePage extends javax.swing.JFrame {
    private final AuthenticationController authenticationController = new AuthenticationController();
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }
    
    private void navigasi(String menu) {
        JFrame frame;
        
        switch(menu) {
            case "karyawan":
                frame = new FormKaryawan();
            break;
            case "keterlambatan":
                frame = new FormKeterlambatan();
            break;
            case "penggajian":
                frame = new FormPenggajian();
            break;
            case "lembur":
                frame = new FormLembur();
            break;
            case "user":
                frame = new FormUser();
            break;
            case "cuti":
                frame = new FormCuti();
            break;
            default:
                frame = new FormJabatan();
        }
        
       frame.setAlwaysOnTop(true);
       frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ic_jabatan = new javax.swing.JLabel();
        lbl_jabatan = new javax.swing.JLabel();
        lbl_karyawan = new javax.swing.JLabel();
        ic_karayawan = new javax.swing.JLabel();
        lbl_terlambat = new javax.swing.JLabel();
        ic_terlambat = new javax.swing.JLabel();
        lbl_penggajian = new javax.swing.JLabel();
        ic_penggajian = new javax.swing.JLabel();
        ic_lembur = new javax.swing.JLabel();
        lbl_lembur = new javax.swing.JLabel();
        ic_user = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        ic_cuti = new javax.swing.JLabel();
        lbl_cuti = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Aplikasi Penggajian");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        ic_jabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_jabatan.png"))); // NOI18N
        ic_jabatan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ic_jabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_jabatanMousePressed(evt);
            }
        });

        lbl_jabatan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_jabatan.setText("Jabatan");
        lbl_jabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_jabatanMousePressed(evt);
            }
        });

        lbl_karyawan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_karyawan.setText("Karyawan");
        lbl_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_karyawanMousePressed(evt);
            }
        });

        ic_karayawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ic_karayawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_karyawan.png"))); // NOI18N
        ic_karayawan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ic_karayawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_karayawanMousePressed(evt);
            }
        });

        lbl_terlambat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_terlambat.setText("Terlamat");
        lbl_terlambat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_terlambatMousePressed(evt);
            }
        });

        ic_terlambat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_terlamat.png"))); // NOI18N
        ic_terlambat.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ic_terlambat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_terlambatMousePressed(evt);
            }
        });

        lbl_penggajian.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_penggajian.setText("Penggajian");
        lbl_penggajian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_penggajianMousePressed(evt);
            }
        });

        ic_penggajian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ic_penggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_penggajian.png"))); // NOI18N
        ic_penggajian.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ic_penggajian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_penggajianMousePressed(evt);
            }
        });

        ic_lembur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_lembur.png"))); // NOI18N
        ic_lembur.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ic_lembur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_lemburMousePressed(evt);
            }
        });

        lbl_lembur.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_lembur.setText("Lembur");
        lbl_lembur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_lemburMousePressed(evt);
            }
        });

        ic_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_admin.png"))); // NOI18N
        ic_user.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ic_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_userMousePressed(evt);
            }
        });

        lbl_user.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_user.setText("User");
        lbl_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_userMousePressed(evt);
            }
        });

        ic_cuti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_cuti.png"))); // NOI18N
        ic_cuti.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ic_cuti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_cutiMousePressed(evt);
            }
        });

        lbl_cuti.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_cuti.setText("Cuti");
        lbl_cuti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_cutiMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_karyawan)
                    .addComponent(ic_karayawan)
                    .addComponent(ic_lembur)
                    .addComponent(lbl_lembur)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(lbl_user)
                        .addComponent(ic_user)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbl_penggajian)
                            .addComponent(ic_penggajian)
                            .addComponent(lbl_terlambat)
                            .addComponent(ic_terlambat))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbl_jabatan)
                            .addComponent(ic_jabatan)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(ic_cuti)
                                .addComponent(lbl_cuti)))))
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ic_karayawan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_karyawan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ic_penggajian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_penggajian))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ic_jabatan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_jabatan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ic_lembur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_lembur))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ic_terlambat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_terlambat)))
                        .addGap(41, 41, 41)
                        .addComponent(ic_user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_user))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ic_cuti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_cuti)))
                .addGap(65, 65, 65))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        final boolean logout = authenticationController.logout();
        
        if(logout) {
            JFrame login = new FormLogin();
            dispose();
            login.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Logout");
        }
      
    }//GEN-LAST:event_jButton1MousePressed

    private void ic_jabatanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_jabatanMousePressed
       navigasi("jabatan");
    }//GEN-LAST:event_ic_jabatanMousePressed

    private void lbl_jabatanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_jabatanMousePressed
       navigasi("jabatan");
    }//GEN-LAST:event_lbl_jabatanMousePressed

    private void lbl_karyawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_karyawanMousePressed
       navigasi("karyawan");
    }//GEN-LAST:event_lbl_karyawanMousePressed

    private void ic_karayawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_karayawanMousePressed
       navigasi("karyawan");
    }//GEN-LAST:event_ic_karayawanMousePressed

    private void ic_terlambatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_terlambatMousePressed
      navigasi("keterlambatan");
    }//GEN-LAST:event_ic_terlambatMousePressed

    private void lbl_terlambatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_terlambatMousePressed
       navigasi("keterlambatan");
    }//GEN-LAST:event_lbl_terlambatMousePressed

    private void ic_penggajianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_penggajianMousePressed
       navigasi("penggajian");
    }//GEN-LAST:event_ic_penggajianMousePressed

    private void lbl_penggajianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_penggajianMousePressed
       navigasi("penggajian");
    }//GEN-LAST:event_lbl_penggajianMousePressed

    private void ic_lemburMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_lemburMousePressed
       navigasi("lembur");
    }//GEN-LAST:event_ic_lemburMousePressed

    private void lbl_lemburMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_lemburMousePressed
       navigasi("lembur");
    }//GEN-LAST:event_lbl_lemburMousePressed

    private void ic_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_userMousePressed
        navigasi("user");
    }//GEN-LAST:event_ic_userMousePressed

    private void lbl_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_userMousePressed
       navigasi("user");
    }//GEN-LAST:event_lbl_userMousePressed

    private void ic_cutiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_cutiMousePressed
       navigasi("cuti");
    }//GEN-LAST:event_ic_cutiMousePressed

    private void lbl_cutiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cutiMousePressed
       navigasi("cuti");
    }//GEN-LAST:event_lbl_cutiMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ic_cuti;
    private javax.swing.JLabel ic_jabatan;
    private javax.swing.JLabel ic_karayawan;
    private javax.swing.JLabel ic_lembur;
    private javax.swing.JLabel ic_penggajian;
    private javax.swing.JLabel ic_terlambat;
    private javax.swing.JLabel ic_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cuti;
    private javax.swing.JLabel lbl_jabatan;
    private javax.swing.JLabel lbl_karyawan;
    private javax.swing.JLabel lbl_lembur;
    private javax.swing.JLabel lbl_penggajian;
    private javax.swing.JLabel lbl_terlambat;
    private javax.swing.JLabel lbl_user;
    // End of variables declaration//GEN-END:variables
}
