/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import authentiocation.AuthenticationController;
import authentiocation.FormLogin;
import jabatan.FormJabatan;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import karyawan.FormKaryawan;
import keterlamabatan.FormKeterlambatan;

/**
 *
 * @author Farhan Fadila
 */
public class HomePage extends javax.swing.JFrame {
    private final AuthenticationController authenticationController = new AuthenticationController();
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }
    
    private void navigasi(String menu) {
        JFrame frame;
        
        switch(menu) {
            case "karyawan":
                frame = new FormKaryawan();
            break;
            case "keterlambatan":
                frame = new FormKeterlambatan();
            break;
            default:
                frame = new FormJabatan();
        }
        
       frame.setAlwaysOnTop(true);
       frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ic_jabatan = new javax.swing.JLabel();
        lbl_jabatan = new javax.swing.JLabel();
        lbl_karyawan = new javax.swing.JLabel();
        ic_karayawan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_terlambat = new javax.swing.JLabel();
        ic_terlambat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Aplikasi Penggajian");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        ic_jabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_jabatan.png"))); // NOI18N
        ic_jabatan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ic_jabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_jabatanMousePressed(evt);
            }
        });

        lbl_jabatan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_jabatan.setText("Jabatan");
        lbl_jabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_jabatanMousePressed(evt);
            }
        });

        lbl_karyawan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_karyawan.setText("Karyawan");
        lbl_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_karyawanMousePressed(evt);
            }
        });

        ic_karayawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ic_karayawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_karyawan.png"))); // NOI18N
        ic_karayawan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ic_karayawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_karayawanMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Kegiatan");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_kegiatan.png"))); // NOI18N
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lbl_terlambat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_terlambat.setText("Terlamat");
        lbl_terlambat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_terlambatMousePressed(evt);
            }
        });

        ic_terlambat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_terlamat.png"))); // NOI18N
        ic_terlambat.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ic_terlambat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ic_terlambatMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Penggajian");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_penggajian.png"))); // NOI18N
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_karyawan)
                    .addComponent(ic_karayawan)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_terlambat)
                    .addComponent(ic_terlambat)
                    .addComponent(lbl_jabatan)
                    .addComponent(ic_jabatan)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ic_jabatan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_jabatan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ic_karayawan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_karyawan)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ic_terlambat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_terlambat)))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        final boolean logout = authenticationController.logout();
        
        if(logout) {
            JFrame login = new FormLogin();
            dispose();
            login.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Logout");
        }
      
    }//GEN-LAST:event_jButton1MousePressed

    private void ic_jabatanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_jabatanMousePressed
       navigasi("jabatan");
    }//GEN-LAST:event_ic_jabatanMousePressed

    private void lbl_jabatanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_jabatanMousePressed
       navigasi("jabatan");
    }//GEN-LAST:event_lbl_jabatanMousePressed

    private void lbl_karyawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_karyawanMousePressed
       navigasi("karyawan");
    }//GEN-LAST:event_lbl_karyawanMousePressed

    private void ic_karayawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_karayawanMousePressed
       navigasi("karyawan");
    }//GEN-LAST:event_ic_karayawanMousePressed

    private void ic_terlambatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ic_terlambatMousePressed
      navigasi("keterlambatan");
    }//GEN-LAST:event_ic_terlambatMousePressed

    private void lbl_terlambatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_terlambatMousePressed
       navigasi("keterlambatan");
    }//GEN-LAST:event_lbl_terlambatMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ic_jabatan;
    private javax.swing.JLabel ic_karayawan;
    private javax.swing.JLabel ic_terlambat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_jabatan;
    private javax.swing.JLabel lbl_karyawan;
    private javax.swing.JLabel lbl_terlambat;
    // End of variables declaration//GEN-END:variables
}
