/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuti;

import jabatan.Jabatan;
import karyawan.KaryawanController;
import jabatan.JabatanController;
import java.awt.HeadlessException;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import karyawan.Karyawan;
import utils.Utils;

/**
 *
 * @author Farhan Fadila
 */
public class FormCuti extends javax.swing.JFrame {
    private final KaryawanController karyawanController = new KaryawanController();
    private final JabatanController jabatanController = new JabatanController();
    private final CutiController cutiController = new CutiController();
    private final Utils utils = new Utils();
    private int selectedId;
    private DefaultTableModel tableModelCuti;
    private DefaultTableModel tableModelKaryawan;
    /**
     * Creates new form FormCuti
     */
    public FormCuti() {
        initComponents();
        initColumnTabel();
        initRowTableKaryawan();
        initRowTableCuti();
        txt_id_karyawan.setEditable(false);
        txt_nama_karyawan.setEditable(false);
    }
    
    private void initColumnTabel() {
        tableModelCuti = new DefaultTableModel();
        tableModelKaryawan = new DefaultTableModel();
        
        tbl_cuti.setModel(tableModelCuti);
        tableModelCuti.addColumn("ID Cuti");
        tableModelCuti.addColumn("ID Karyawan");
        tableModelCuti.addColumn("Nama Karyawan");
        tableModelCuti.addColumn("Tanggal");
        tableModelCuti.addColumn("Jumlah Hari");
        tableModelCuti.addColumn("Keterangan");
        
        tbl_karyawan.setModel(tableModelKaryawan);
        tableModelKaryawan.addColumn("ID Karyawan");
        tableModelKaryawan.addColumn("Nama Karyawan");
        tableModelKaryawan.addColumn("Jabatan");
    }
    
    private void initRowTableCuti() {
       tableModelCuti.getDataVector().removeAllElements();
       tableModelCuti.fireTableDataChanged();
       try {
            List<Cuti> dataCuti = cutiController.dataCuti();
            
            
            dataCuti.stream().map((item) -> {
                Object[] obj = new Object[6];
                Karyawan karyawan = karyawanController.detailKaryawan(item.idKaryawan);
                obj[0] = item.id;
                obj[1] = item.idKaryawan;
                obj[2] = karyawan.nama;
                obj[3] = utils.dMY(utils.toDate(item.tanggal));
                obj[4] = item.jumlahHari;
                obj[5] = item.keterangan;
               return obj;
           }).forEachOrdered((obj) -> { 
               tableModelCuti.addRow(obj);
           });
           
       } catch(Exception ex) {
           System.out.println("initRowTableCuti ERROR" + ex);
       }
    }
    
    private void initRowTableKaryawan() {
       tableModelKaryawan.getDataVector().removeAllElements();
       tableModelKaryawan.fireTableDataChanged();
       try {
            List<Karyawan> karyawan = karyawanController.dataKaryawan(false);
            
            
            karyawan.stream().map((item) -> {
                Object[] obj = new Object[4];
                Jabatan jabatan = jabatanController.detailJabatan(item.idJabatan);
                obj[0] = item.id;
                obj[1] = item.nama;
                obj[2] = jabatan.namaJabatan;
               return obj;
           }).forEachOrdered((obj) -> { 
               tableModelKaryawan.addRow(obj);
           });
           
       } catch(Exception ex) {
           System.out.println("initRowTableKaryawan ERROR" + ex);
       }
    }
    
    private void resetForm() {
        txt_id_karyawan.setText("");
        txt_nama_karyawan.setText("");
        txt_keterangan.setText("");
        spn_tanggal.setDate(new Date());
        spn_hari.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        spn_tanggal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_karyawan = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_id_karyawan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        txt_nama_karyawan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_keterangan = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_cuti = new javax.swing.JTable();
        btn_reset = new javax.swing.JButton();
        spn_hari = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Form Cuti");

        jLabel2.setText("Tanggal");

        jLabel3.setText("Jumlah Hari");

        tbl_karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_karyawanMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_karyawan);

        jLabel4.setText("Nama Karyawan");

        jLabel5.setText("ID Karyawan");

        btn_tambah.setBackground(new java.awt.Color(0, 204, 0));
        btn_tambah.setText("Tambah");
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_tambahMousePressed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(255, 204, 51));
        btn_edit.setText("Edit");
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editMousePressed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(255, 51, 51));
        btn_hapus.setText("Hapus");
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_hapusMousePressed(evt);
            }
        });

        jLabel6.setText("Keterangan");

        txt_keterangan.setColumns(20);
        txt_keterangan.setRows(5);
        jScrollPane2.setViewportView(txt_keterangan);

        tbl_cuti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_cuti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_cutiMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_cuti);

        btn_reset.setBackground(new java.awt.Color(0, 204, 204));
        btn_reset.setText("Reset");
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_resetMousePressed(evt);
            }
        });

        spn_hari.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(spn_tanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_nama_karyawan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_id_karyawan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(spn_hari, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus)
                        .addGap(18, 18, 18)
                        .addComponent(btn_reset)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_nama_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(spn_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spn_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(38, 38, 38)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_tambah)
                            .addComponent(btn_hapus)
                            .addComponent(btn_edit)
                            .addComponent(btn_reset)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMousePressed
        try {
            String idKaryawan = txt_id_karyawan.getText();
            long tanggal = utils.toEpoch(spn_tanggal.getDate());
            int jumlahHari = Integer.parseInt(spn_hari.getModel().getValue().toString());
            String keterangan = txt_keterangan.getText();
            
            boolean sukses = cutiController.tambah(idKaryawan, tanggal, jumlahHari, keterangan);
            
             if(sukses) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
                initRowTableCuti();
                resetForm();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambah data");
            }
        } catch(HeadlessException | NumberFormatException ex) {
            System.out.println("Buton Tambah Exception => " + ex);
        }
    }//GEN-LAST:event_btn_tambahMousePressed

    private void btn_editMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMousePressed
        try {
            String idKaryawan = txt_id_karyawan.getText();
            long tanggal = utils.toEpoch(spn_tanggal.getDate());
            int jumlahHari = Integer.parseInt(spn_hari.getModel().getValue().toString());
            String keterangan = txt_keterangan.getText();

            boolean edit =  cutiController.edit(selectedId, idKaryawan, tanggal, jumlahHari, keterangan);

            if(edit) {
                JOptionPane.showMessageDialog(this, "Data berhasil diedit!");
                initRowTableCuti();
                resetForm();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengedit data!");
            }

        } catch(HeadlessException | NumberFormatException ex) {
            System.out.println("Buton Edit Exception => " + ex);
        }
    }//GEN-LAST:event_btn_editMousePressed

    private void btn_hapusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMousePressed
        try {
            final boolean sukses = cutiController.hapus(selectedId);
            initRowTableCuti();
            resetForm();
        } catch(Exception ex) {
            System.out.println("Buton Edit Exception => " + ex);
        }
    }//GEN-LAST:event_btn_hapusMousePressed

    private void tbl_karyawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_karyawanMousePressed
        int index = tbl_karyawan.getSelectedRow();
        TableModel mdl = tbl_karyawan.getModel();
        String idKaryawan = mdl.getValueAt(index, 0).toString();
        String namaKaryawan = mdl.getValueAt(index, 1).toString();
        txt_id_karyawan.setText(idKaryawan);
        txt_nama_karyawan.setText(namaKaryawan);
    }//GEN-LAST:event_tbl_karyawanMousePressed

    private void btn_resetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMousePressed
        resetForm();
    }//GEN-LAST:event_btn_resetMousePressed

    private void tbl_cutiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cutiMousePressed
       try {
            int index = tbl_cuti.getSelectedRow();
            TableModel mdl = tbl_cuti.getModel();
            String id = mdl.getValueAt(index, 0).toString();
            Cuti cuti = cutiController.detailCuti(id);
            String idKaryawan = mdl.getValueAt(index, 1).toString();
            String namaKaryawan = mdl.getValueAt(index, 2).toString();
            String jumlahHari = mdl.getValueAt(index, 4).toString();
           
            txt_id_karyawan.setText(idKaryawan);
            txt_nama_karyawan.setText(namaKaryawan);
            spn_tanggal.setDate(utils.toDate(cuti.tanggal));
            spn_hari.setValue(Integer.parseInt(jumlahHari));
            txt_keterangan.setText(cuti.keterangan);
            selectedId = cuti.id;
       } catch(Exception ex) {
            System.out.println(ex);
       }
    }//GEN-LAST:event_tbl_cutiMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCuti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCuti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambah;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner spn_hari;
    private com.toedter.calendar.JDateChooser spn_tanggal;
    private javax.swing.JTable tbl_cuti;
    private javax.swing.JTable tbl_karyawan;
    private javax.swing.JTextField txt_id_karyawan;
    private javax.swing.JTextArea txt_keterangan;
    private javax.swing.JTextField txt_nama_karyawan;
    // End of variables declaration//GEN-END:variables
}
